name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Thank you for taking the time to report an issue! Please fill out the details below to help us understand the problem.
        
        > **Note:** This is a personal project maintained in spare time. While we appreciate bug reports, we cannot guarantee quick fixes or provide extensive support. The project is provided "as-is" but we'll do our best to address critical issues when possible.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what went wrong
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Start playing a movie in Plex
        2. Wait for webhook to trigger
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The subtitle should have been downloaded and selected automatically...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Error message or unexpected behavior...
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running plexsubs?
      options:
        - Docker
        - Python/uv (manual)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of plexsubs are you using? (if known)
      placeholder: e.g., 0.1.0 or commit hash

  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: If running manually, what Python version?
      placeholder: e.g., 3.11.4

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste relevant log output (with any sensitive info redacted)
      placeholder: Paste logs here...
      render: shell
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration (without secrets!)
      description: Your configuration settings (REMOVE sensitive info like tokens/passwords)
      placeholder: |
        PLEX_URL=http://localhost:32400
        SUBTITLES_LANGUAGES=en
        ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
      placeholder: Media file type, subtitle provider used, etc.
